import type { Collection } from "../types";

export const collections: Collection[] = [
  {
    id: "1",
    name: "Modern Minimalist",
    slug: "modern-minimalist",
    description: "Linhas limpas, cores neutras e design funcional para uma casa contemporânea.",
    featured: [
      {
        id: "1-1",
        url: "/mm2.jpg?height=300&width=400",
        alt: "ceramic vases on a shelf",
        title: "Trio Formas Únicas",
        price: 235,
        shopUrl: "#",
      },
      {
        id: "1-2",
        url: "/mm3.jpg?height=300&width=400",
        alt: "Minimalist dining area",
        title: "Dupla Arte Singela",
        price: 248,
        shopUrl: "#",
      },
      {
        id: "1-3",
        url: "/mm4.jpg?height=300&width=400",
        alt: "Sweet home",
        title: "Elegance Confortável",
        price: 250,
        shopUrl: "#",
      },
      {
        id: "1-4",
        url: "/mm1.jpg?height=300&width=400",
        alt: "Minimalist art display",
        title: "Par Conforto Puro",
        price: 299,
        shopUrl: "#",
      },
      {
        id: "1-5",
        url: "/mm5.jpg?height=300&width=400",
        alt: "Elegant support",
        title: "Suporte Elegance",
        price: 150,
        shopUrl: "#",
      },
    ],
    images: [],
  },
  {
    id: "2",
    name: "Bohemian Chic",
    slug: "bohemian-chic",
    description: "Padrões ecléticos, texturas ricas e cores vibrantes para uma estética de espírito livre.",
    featured: [
      {
        id: "2-1",
        url: "/bc1.jpg?height=300&width=400",
        alt: "Bohemian living space",
        title: "Azul Boho Celeste",
        price: 50,
        shopUrl: "#",
      },
      {
        id: "2-2",
        url: "/bc2.jpg?height=300&width=400",
        alt: "Boho bedroom decor",
        title: "Trama Natural Boho",
        price: 79,
        shopUrl: "#",
      },
      {
        id: "2-3",
        url: "/bc3.jpg?height=300&width=400",
        alt: "Wall hanging",
        title: "Entrelaço Livre",
        price: 30,
        shopUrl: "#",
      },
      {
        id: "2-4",
        url: "/bc4.jpg?height=300&width=400",
        alt: "Boho urban light",
        title: "Luz Rústica Urbana",
        price: 375,
        shopUrl: "#",
      },
      {
        id: "2-5",
        url: "/bc5.jpg?height=300&width=400",
        alt: "Nomadic textile art",
        title: "Arte Têxtil Nômade",
        price: 159,
        shopUrl: "#",
      },
    ],
    images: [],
  },
  {
    id: "3",
    name: "Industrial Loft",
    slug: "industrial-loft",
    description: "Matérias-primas, elementos expostos e estética urbana para o morador moderno da cidade.",
    featured: [
      {
        id: "3-1",
        url: "/il1.jpg?height=300&width=400",
        alt: "Industrial living room",
        title: "Chama Concreta",
        price: 599,
        shopUrl: "#",
      },
      {
        id: "3-2",
        url: "/il2.jpg?height=300&width=400",
        alt: "Raw green base",
        title: "Base Verde Bruta",
        price: 399,
        shopUrl: "#",
      },
      {
        id: "3-3",
        url: "/il3.jpg?height=300&width=400",
        alt: "Textured loft decor",
        title: "Textura Loft Tátil",
        price: 749,
        shopUrl: "#",
      },
      {
        id: "3-4",
        url: "/il4.jpg?height=300&width=400",
        alt: "Industrial bedroom",
        title: "Trançado Industrial",
        price: 289,
        shopUrl: "#",
      },
      {
        id: "3-5",
        url: "/il5.jpg?height=300&width=400",
        alt: "Urban bedroom style",
        title: "Estante Aço Firme",
        price: 899,
        shopUrl: "#",
      },
    ],
    images: [],
  },
  {
    id: "4",
    name: "Coastal Retreat",
    slug: "coastal-retreat",
    description: "Espaços claros e arejados com cores inspiradas no oceano e texturas naturais.",
    featured: [
      {
        id: "4-1",
        url: "/cr1.jpg?height=300&width=400",
        alt: "Coastal living room",
        title: "Coqueiro Marítimo",
        price: 699,
        shopUrl: "#",
      },
      {
        id: "4-2",
        url: "/cr2.jpg?height=300&width=400",
        alt: "Oceanic art",
        title: "Peixe das Ondas",
        price: 129,
        shopUrl: "#",
      },
      {
        id: "4-3",
        url: "/cr3.jpg?height=300&width=400",
        alt: "Ocean-inspired decor",
        title: "Costura da Costa",
        price: 199,
        shopUrl: "#",
      },
      {
        id: "4-4",
        url: "/cr4.jpg?height=300&width=400",
        alt: "Ocean treasure",
        title: "Tesouro do Mar",
        price: 249,
        shopUrl: "#",
      },
      {
        id: "4-5",
        url: "/cr5.jpg?height=300&width=400",
        alt: "Woven coastal rug",
        title: "Areia Tecida",
        price: 459,
        shopUrl: "#",
      },
    ],
    images: [],
  },
  {
    id: "5",
    name: "Vintage Farmhouse",
    slug: "vintage-farmhouse",
    description: "O charme rústico encontra o conforto moderno com madeiras envelhecidas e itens vintage.",
    featured: [
      {
        id: "5-1",
        url: "/vf1.jpg?height=300&width=400",
        alt: "Farmhouse kitchen",
        title: "Trama da Vovó",
        price: 899,
        shopUrl: "#",
      },
      {
        id: "5-2",
        url: "/vf2.jpg?height=300&width=400",
        alt: "Rustic nest",
        title: "Ninho Rústico",
        price: 1299,
        shopUrl: "#",
      },
      {
        id: "5-3",
        url: "/vf3.jpg?height=300&width=400",
        alt: "Farmhouse light",
        title: "Luz da Fazenda",
        price: 799,
        shopUrl: "#",
      },
      {
        id: "5-4",
        url: "/vf4.jpg?height=300&width=400",
        alt: "Barn embroidery",
        title: "Bordado do Celeiro",
        price: 89,
        shopUrl: "#",
      },
      {
        id: "5-5",
        url: "/vf5.jpg?height=300&width=400",
        alt: "Farmhouse table",
        title: "Mesa Campestre Tecida",
        price: 179,
        shopUrl: "#",
      },
    ],
    images: [],
  },
]
